- name: Install Control Plane
  hosts: all
  gather_facts: true
  become: yes

  tasks:
    - name: Install the rke2-server service and the rke2 binary
      shell: |
        curl -sfL https://get.rke2.io | sh -
        mkdir -p /etc/rancher/rke2/

    - name: Disable nginx
      copy:
        dest: /etc/rancher/rke2/config.yaml
        content: |
          disable: rke2-ingress-nginx

    - name: Enable and Start the service
      shell: |
        systemctl enable rke2-server.service
        systemctl start rke2-server.service

    - name: Retrieve kubeconfig
      command: cat /etc/rancher/rke2/rke2.yaml
      register: context

    - name: Retrieve node-token to register other server or agent nodes
      command: cat /var/lib/rancher/rke2/server/node-token
      register: node_token

    - name: Copy kubeconfig to local file
      local_action:
        module: copy
        content: "{{ context.stdout }}"
        dest: "/tmp/kubeconfig_temp"

    - name: Copy node-token to local file
      local_action:
        module: copy
        content: "{{ node_token.stdout_lines[0] }}"
        dest: "/tmp/nodetoken_temp"

    - name: Merge kubeconfig rke2 with current
      become_method: sudo
      delegate_to: localhost
      shell: |
        sed -i 's/default/{{ NAME }}/g' /tmp/kubeconfig_temp
        sed -i 's/127.0.0.1/{{ ansible_facts.default_ipv4.address }}/g' /tmp/kubeconfig_temp
        KUBECONFIG=~/.kube/config:/tmp/kubeconfig_temp kubectl config view --flatten
      register: kubeconfig

    - name: Replace kubeconfig host
      delegate_to: localhost
      copy:
        content: "{{ kubeconfig.stdout }}"
        dest: "{{ playbook_dir }}/../kubeconfig"
